
# Configuration sample for multibutton.pl

# Set logging level (logging goes to STDERR/journalctl). Allowed values are: DEBUG, INFO, WARN, ERROR, FATAL

logging: INFO

# Set updatePeriod to the number of microseconds between key presses checks
# Default is 200ms between key presses

updatePeriod: 200000

# Set bufferSize to how many keys to keep in memory when analizing a multiple key press.
# The larger the value, the more time you have to wait until any action executes

bufferSize: 10

# Set longPress to a fraction - how many times does a key have to appear in a sequence before considering it a long press.
# The default is 0.7 which means 70% of the keys in bufferSize have to be the same to register as a long press

longPress: 0.7

# The following section defines possible key sequences and an action that should be executed in the background
# Note that the command runs as the same user you run multibutton.pl by default

# Example commands (one line each):
#KEY_CAMERA: logger "Key has been pressed"
#KEY_CAMERA-KEY_CAMERA: logger "Key has been double pressed"; logger "Two commands have been executed"
#KEY_CAMERA-KEY_CAMERA-KEY_CAMERA: su -c "logger 'Tripleclick - This command is run as a different user (uid $EUID)'" odroid
#LONGKEY_CAMERA: DISPLAY=:0 xeyes

KEY_CAMERA: logger -s 'Pressed single'
KEY_CAMERA-KEY_CAMERA: logger -s 'Pressed double'
KEY_CAMERA-KEY_CAMERA-KEY_CAMERA: logger -s 'Pressed triple'
LONGKEY_CAMERA: logger -s 'Pressed long'
